language: emacs-lisp
cache:
  - apt: true
  - http: false
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_install:
  - ln -s $TRAVIS_BUILD_DIR $HOME/.emacs.d
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
script:
  - make EMACS=$EMACS
  - make clean
